name: Lint and Test
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  test:
    name: Test Components
    
    strategy:
      matrix:
        node-version: [18.16.1, 'latest']
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint
        run: npm run lint

      - name: Run Tests
        if: always()
        run: npm run test